theme: jekyll-theme-minimal
author:
  name: "Saad Khan"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am an **amazing** person." # Note: Markdown is allowed
  location: "Chicago, IL"
  links:
    - label: "Made Mistakes"
      icon: "/assets/images/bio-photo.jpg"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "/assets/images/bio-photo.jpg"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "/assets/images/bio-photo.jpg"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "/assets/images/bio-photo.jpg"
      url: "https://instagram.com/mmistakes"
